import { useEffect, useRef, useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { api, Row, SiteCodeType } from "../api";
import ThemeNamePicker, { ThemeSelection } from "./ThemeNamePicker";
import { friendlyError } from "./EntityGrid";

/**
 * FEAT-1 — tri-mode editor for a site's ``simple_name`` (the "site code").
 *
 * The site code can be produced three ways:
 *
 * * **auto**   — ``org + campus + region + sequence`` (e.g. ``vfhmcc1``),
 *                computed by the backend and refreshed whenever the lookups
 *                change. Read-only here.
 * * **custom** — whatever the operator types.
 * * **theme**  — a name picked from the built-in themed catalogues (FEAT-3);
 *                stored in ``theme_name`` / ``theme_category`` and mirrored
 *                into ``simple_name``.
 *
 * The panel edits the row currently selected in the Sites grid. Nothing is
 * written until "Save site code" is pressed, so switching modes to compare the
 * resulting code is free.
 */

const MODES: { value: SiteCodeType; label: string; blurb: string }[] = [
  {
    value: "auto",
    label: "Auto",
    blurb: "Organization + campus + region + sequence, generated by the server.",
  },
  {
    value: "custom",
    label: "Custom",
    blurb: "Type any code you like — it is stored verbatim.",
  },
  {
    value: "theme",
    label: "Theme",
    blurb: "Pick a memorable name from a themed catalogue.",
  },
];

interface Props {
  /** Row selected in the grid, or null when nothing is selected. */
  site: Row | null;
}

export default function SiteCodePanel({ site }: Props) {
  const qc = useQueryClient();
  const [mode, setMode] = useState<SiteCodeType>("auto");
  const [custom, setCustom] = useState("");
  const [theme, setTheme] = useState<ThemeSelection | null>(null);
  const [pickerOpen, setPickerOpen] = useState(false);
  const [autoCode, setAutoCode] = useState("");
  const [autoMissing, setAutoMissing] = useState<string[]>([]);
  const [autoLoading, setAutoLoading] = useState(false);
  const [message, setMessage] = useState("");
  // Guards against an older /naming/site-code answer landing last.
  const seq = useRef(0);

  const siteId = site?.id ?? null;

  // Adopt the persisted values whenever a different row is selected or the
  // grid refetches the current one.
  useEffect(() => {
    setMessage("");
    if (!site) {
      setMode("auto");
      setCustom("");
      setTheme(null);
      return;
    }
    setMode((site.site_code_type as SiteCodeType) || "auto");
    setCustom(site.simple_name ?? "");
    setTheme(
      site.theme_name
        ? { name: site.theme_name, category: site.theme_category ?? "" }
        : null,
    );
  }, [
    siteId,
    site?.site_code_type,
    site?.simple_name,
    site?.theme_name,
    site?.theme_category,
  ]);

  // What the server would generate for this row's org / campus / region.
  useEffect(() => {
    if (!site) {
      setAutoCode("");
      setAutoMissing([]);
      return;
    }
    const mine = ++seq.current;
    setAutoLoading(true);
    api
      .siteCode(
        site.organization_id,
        site.campus_id,
        site.region_id,
        site.id,
      )
      .then((r) => {
        if (seq.current !== mine) return;
        setAutoCode(r.site_code);
        setAutoMissing(r.missing ?? []);
      })
      .catch(() => {
        if (seq.current !== mine) return;
        setAutoCode("");
        setAutoMissing([]);
      })
      .finally(() => {
        if (seq.current === mine) setAutoLoading(false);
      });
  }, [siteId, site?.organization_id, site?.campus_id, site?.region_id]);

  const saveMut = useMutation({
    mutationFn: ({ id, payload }: { id: number; payload: Row }) =>
      api.update("sites", id, payload),
    onSuccess: (row: Row) => {
      qc.invalidateQueries({ queryKey: ["sites"] });
      setMessage(`Saved — site code is now “${row?.simple_name ?? ""}”.`);
    },
    onError: (e: Error) => setMessage(friendlyError(e.message)),
  });

  if (!site) {
    return (
      <div className="mb-2 px-3 py-2 border border-dashed border-slate-300 rounded text-sm text-slate-500">
        <span className="font-medium text-slate-600">Site code</span> — select a
        row to choose how its code is generated (auto, custom or themed).
      </div>
    );
  }

  const effective =
    mode === "auto" ? autoCode : mode === "theme" ? theme?.name ?? "" : custom.trim();

  const dirty =
    mode !== ((site.site_code_type as SiteCodeType) || "auto") ||
    (mode === "custom" && custom.trim() !== (site.simple_name ?? "")) ||
    (mode === "theme" && (theme?.name ?? "") !== (site.theme_name ?? ""));

  const blocked =
    (mode === "custom" && custom.trim() === "") ||
    (mode === "theme" && !theme) ||
    (mode === "auto" && autoCode === "");

  const handleSave = () => {
    setMessage("");
    const payload: Row = { site_code_type: mode };
    if (mode === "custom") {
      payload.simple_name = custom.trim();
    } else if (mode === "theme" && theme) {
      // generate_site() mirrors theme_name into simple_name server-side; send
      // it too so the change is recorded even if naming is a no-op.
      payload.theme_name = theme.name;
      payload.theme_category = theme.category;
      payload.simple_name = theme.name;
    }
    saveMut.mutate({ id: site.id, payload });
  };

  const active = MODES.find((m) => m.value === mode);

  return (
    <div className="mb-2 px-3 py-2.5 border border-slate-200 bg-slate-50 rounded">
      <div className="flex flex-wrap items-center gap-x-4 gap-y-2">
        <span className="text-sm font-medium text-slate-700">
          Site code for #{site.id}
        </span>

        <div className="flex gap-3">
          {MODES.map((m) => (
            <label
              key={m.value}
              className="flex items-center gap-1.5 text-sm text-slate-700 cursor-pointer"
              title={m.blurb}
            >
              <input
                type="radio"
                name="site-code-mode"
                checked={mode === m.value}
                onChange={() => {
                  setMode(m.value);
                  setMessage("");
                }}
              />
              {m.label}
            </label>
          ))}
        </div>

        {mode === "auto" && (
          <span className="text-sm">
            <code className="px-2 py-1 bg-white border border-slate-300 rounded text-slate-800">
              {autoLoading ? "…" : autoCode || "—"}
            </code>
            {!autoLoading && autoMissing.length > 0 && (
              <span className="ml-2 text-xs text-amber-700">
                needs {autoMissing.join(", ")}
              </span>
            )}
          </span>
        )}

        {mode === "custom" && (
          <input
            value={custom}
            onChange={(e) => setCustom(e.target.value)}
            placeholder="e.g. hq-bogota-1"
            className="border border-slate-300 rounded px-2 py-1 text-sm w-56"
          />
        )}

        {mode === "theme" && (
          <span className="flex items-center gap-2 text-sm">
            <button
              onClick={() => setPickerOpen(true)}
              className="px-3 py-1 border border-slate-300 bg-white rounded text-sm hover:bg-slate-100"
            >
              {theme ? "Change…" : "Pick a name…"}
            </button>
            <code className="px-2 py-1 bg-white border border-slate-300 rounded text-slate-800">
              {theme?.name ?? "—"}
            </code>
          </span>
        )}

        <button
          onClick={handleSave}
          disabled={!dirty || blocked || saveMut.isPending}
          className="px-3 py-1.5 bg-blue-600 text-white rounded text-sm hover:bg-blue-700 disabled:opacity-40 disabled:cursor-not-allowed"
        >
          {saveMut.isPending ? "Saving…" : "Save site code"}
        </button>
      </div>

      <p className="text-xs text-slate-500 mt-1.5">
        {active?.blurb} Resulting code:{" "}
        <span className="font-medium text-slate-700">{effective || "—"}</span>.
        The VF long / short / TIA-606-B names are generated separately and are
        not affected by this choice.
      </p>

      {message && (
        <p
          className={`text-xs mt-1 ${
            saveMut.isError ? "text-red-700" : "text-green-700"
          }`}
        >
          {message}
        </p>
      )}

      <ThemeNamePicker
        open={pickerOpen}
        initialCategory={theme?.category}
        selectedName={theme?.name ?? null}
        onSelect={(sel) => {
          setTheme(sel);
          setPickerOpen(false);
          setMessage("");
        }}
        onClose={() => setPickerOpen(false)}
      />
    </div>
  );
}
