"""Generic async CRUD service with automatic changelog + naming.

Every create/update/delete records field-level entries in ``change_log`` and
re-computes auto-generated name fields via the naming engine.
"""
from __future__ import annotations

from typing import Any, Optional

from sqlalchemy import inspect, select
from sqlalchemy.ext.asyncio import AsyncSession

from . import abbrev, models, naming

# Auto-generated columns must never be set directly by clients.
COMPUTED_FIELDS = {
    "vf_long_name",
    "vf_short_name",
    "tia606b_name",
    "vf_friendly_name",
    "created_at",
    "updated_at",
    "id",
}

# Per-model computed columns that must never be set directly by clients. Kept
# separate from the global COMPUTED_FIELDS because these column names (e.g.
# "label") are legitimately user-editable on OTHER models.
MODEL_COMPUTED_FIELDS: dict = {
    # FEAT-6 (6C): Cable.label is generated by naming.generate_cable.
    models.Cable: {"label"},
}


def _columns(model) -> set[str]:
    return {c.key for c in inspect(model).columns}


def _to_str(value: Any) -> Optional[str]:
    if value is None:
        return None
    return str(value)


def sanitize_payload(model, payload: dict) -> dict:
    cols = {c.key: c for c in inspect(model).columns}
    computed = COMPUTED_FIELDS | MODEL_COMPUTED_FIELDS.get(model, set())
    clean: dict[str, Any] = {}
    for key, value in payload.items():
        if key in computed:
            continue
        if key in cols:
            if isinstance(value, str) and value.strip() == "":
                value = None
            if value is None:
                column = cols[key]
                # A cleared value on a NOT NULL column that has a default must
                # fall back to that default (e.g. site_code_type -> "auto")
                # instead of being written as an explicit NULL.
                if not column.nullable and (
                    column.default is not None or column.server_default is not None
                ):
                    continue
            clean[key] = value
    return clean


def humanize_field(field: str) -> str:
    """Turn a column name into the label the UI shows ("site_id" -> "Site")."""
    name = field[:-3] if field.endswith("_id") else field
    return name.replace("_", " ").strip().title()


def missing_required(model, obj) -> list[str]:
    """Columns the database declares NOT NULL that are still unset.

    Columns with a Python-side or server-side default are skipped: SQLAlchemy /
    PostgreSQL fills those in on flush.
    """
    missing: list[str] = []
    for col in inspect(model).columns:
        if col.primary_key or col.nullable:
            continue
        if col.default is not None or col.server_default is not None:
            continue
        if getattr(obj, col.key, None) is None:
            missing.append(col.key)
    return missing


def validate_required(model, obj) -> None:
    """Raise a readable 422 instead of letting Postgres emit a NOT NULL error.

    The frontend surfaces ``detail`` verbatim in its error toast, so the message
    must name the fields in the same words the grid headers use (BUG-C).
    """
    missing = missing_required(model, obj)
    if not missing:
        return
    from fastapi import HTTPException

    labels = ", ".join(f"'{humanize_field(f)}'" for f in missing)
    plural = "s" if len(missing) > 1 else ""
    raise HTTPException(
        status_code=422,
        detail=(
            f"Missing required field{plural}: {labels}. "
            f"Set {'them' if len(missing) > 1 else 'it'} on the row before saving "
            f"— the database does not allow empty values here."
        ),
    )


async def _validate_abbrev(session: AsyncSession, obj, entity_id) -> None:
    """Normalise the abbreviation/code and validate charset + global uniqueness.

    Runs BEFORE the row is flushed so clients receive a clean 422/409 error
    instead of a raw database CHECK / unique-index violation. The value is
    normalised in place according to the record's ``case_enforcement``.
    """
    field = abbrev.ABBR_FIELDS.get(type(obj))
    if field is None:
        return
    value = getattr(obj, field, None)
    if not value:
        return
    value = abbrev.apply_case(value, getattr(obj, "case_enforcement", None))
    setattr(obj, field, value)
    abbrev.validate_charset(value, field)
    conflict = await abbrev._conflict(
        session, value, obj.__tablename__, entity_id
    )
    if conflict is not None:
        from fastapi import HTTPException

        raise HTTPException(
            status_code=409,
            detail=(
                f"Abbreviation '{value}' is already used by "
                f"{conflict.entity_type} #{conflict.entity_id}. "
                "Abbreviations must be globally unique (case-insensitive)."
            ),
        )


async def _sync_abbrev(session: AsyncSession, obj) -> None:
    """Write / update / remove the global registry row for a saved record.

    The value was already normalised + validated by ``_validate_abbrev`` before
    flush; this only persists the registry ownership row.
    """
    field = abbrev.ABBR_FIELDS.get(type(obj))
    if field is None:
        return
    value = getattr(obj, field, None)
    await abbrev.sync_registry(
        session, obj.__tablename__, obj.id, field, value or None
    )


import ipaddress as _ip


def _http409(detail: str):
    from fastapi import HTTPException

    return HTTPException(status_code=409, detail=detail)


async def _validate_vlan_unique(session: AsyncSession, obj, entity_id) -> None:
    """Enforce GLOBAL uniqueness of ``vlan_id`` across all sites (decision Q1).

    A VLAN number may exist on only one site. Raises a clean 409 explaining the
    conflict instead of surfacing a raw unique-index violation.
    """
    vlan_id = getattr(obj, "vlan_id", None)
    if vlan_id is None:
        return
    stmt = select(models.Vlan).where(models.Vlan.vlan_id == vlan_id)
    if entity_id is not None:
        stmt = stmt.where(models.Vlan.id != entity_id)
    existing = (await session.execute(stmt)).scalars().first()
    if existing is not None:
        raise _http409(
            f"VLAN ID {vlan_id} is already in use globally"
            f" (site #{existing.site_id})."
            " VLAN IDs must be unique across all sites."
        )


async def _validate_cidr_overlap(session: AsyncSession, obj, entity_id) -> None:
    """Reject overlapping CIDRs.

    * Within the same site: any overlap is rejected (decision Q2).
    * Across sites: the *same* network may not be reused (decision Q1/Q2).
      Non-identical overlaps across different sites are allowed (different sites
      legitimately reuse private ranges).
    """
    cidr = getattr(obj, "network_cidr", None)
    if not cidr:
        return
    try:
        new_net = _ip.ip_network(str(cidr), strict=False)
    except ValueError:
        return  # invalid CIDR handled elsewhere
    model = type(obj)
    site_id = getattr(obj, "site_id", None)
    rows = (await session.execute(select(model))).scalars().all()
    for other in rows:
        if entity_id is not None and other.id == entity_id:
            continue
        if not other.network_cidr:
            continue
        try:
            other_net = _ip.ip_network(str(other.network_cidr), strict=False)
        except ValueError:
            continue
        if other_net.version != new_net.version:
            continue
        same_site = site_id is not None and other.site_id == site_id
        if same_site and new_net.overlaps(other_net):
            raise _http409(
                f"CIDR {new_net} overlaps existing segment {other_net}"
                f" (subnet #{other.id}) in the same site."
                " Overlapping subnets are not allowed within a site."
            )
        if not same_site and new_net == other_net:
            raise _http409(
                f"CIDR {new_net} is already used by site #{other.site_id}"
                f" (subnet #{other.id})."
                " The same network may not be reused on another site."
            )


async def _validate_ipam(session: AsyncSession, obj, entity_id) -> None:
    """Dispatch IPAM integrity checks based on the model type."""
    if isinstance(obj, models.Vlan):
        await _validate_vlan_unique(session, obj, entity_id)
    elif isinstance(obj, (models.SubnetIpv4, models.SubnetIpv6)):
        await _validate_cidr_overlap(session, obj, entity_id)


# FEAT-6 (6C): accepted cable media categories. cable_type stays a String
# column (no enum migration); this guard enforces the allowed set in code.
CABLE_TYPES = {"copper", "fiber", "power", "patchcord", "structured"}


def _validate_cable(obj: "models.Cable") -> None:
    """Validate a Cable before flush (runs on create + update).

    * ``cable_type`` must be one of CABLE_TYPES  -> 422
    * a cable may not connect a port to itself   -> 400
    """
    from fastapi import HTTPException

    cable_type = (obj.cable_type or "").strip().lower()
    if cable_type and cable_type not in CABLE_TYPES:
        raise HTTPException(
            status_code=422,
            detail=(
                f"Invalid cable_type '{obj.cable_type}'. Allowed values: "
                + ", ".join(sorted(CABLE_TYPES))
                + "."
            ),
        )
    # Self-connect: same end referenced on both A and B (type + id both set
    # and equal). Empty ends are allowed (a half-recorded cable).
    a = (obj.port_a_type, obj.port_a_id)
    b = (obj.port_b_type, obj.port_b_id)
    if a[1] is not None and b[1] is not None:
        a_norm = ((a[0] or "").strip().lower(), a[1])
        b_norm = ((b[0] or "").strip().lower(), b[1])
        if a_norm == b_norm:
            raise HTTPException(
                status_code=400,
                detail="A cable cannot connect a port to itself.",
            )


async def _validate_model(session: AsyncSession, obj, entity_id) -> None:
    """Model-specific validation dispatch (beyond abbrev + IPAM)."""
    if isinstance(obj, models.Cable):
        _validate_cable(obj)


async def _autoreserve_gateway(session: AsyncSession, obj) -> None:
    """Auto-create a locked "Gateway" reservation for an IPv4 subnet (Q6).

    When a subnet is created with a gateway value, one locked reservation is
    created for it. Idempotent: skips if a gateway reservation already exists.
    """
    if not isinstance(obj, models.SubnetIpv4):
        return
    gateway = getattr(obj, "gateway", None)
    if not gateway:
        return
    gw = str(gateway).split("/")[0]
    existing = (
        await session.execute(
            select(models.SubnetRoleAssignment).where(
                models.SubnetRoleAssignment.subnet_ipv4_id == obj.id,
                models.SubnetRoleAssignment.ipv4_address == gw,
            )
        )
    ).scalars().first()
    if existing is not None:
        return
    session.add(
        models.SubnetRoleAssignment(
            subnet_ipv4_id=obj.id,
            role="gateway",
            label="Gateway",
            ipv4_address=gw,
            is_locked=True,
        )
    )


async def _log(
    session: AsyncSession,
    table: str,
    record_id: int,
    field: str,
    old: Any,
    new: Any,
    source: str,
) -> None:
    session.add(
        models.ChangeLog(
            table_name=table,
            record_id=record_id,
            field_name=field,
            old_value=_to_str(old),
            new_value=_to_str(new),
            change_source=source,
        )
    )


async def list_items(
    session: AsyncSession, model, limit: int = 1000, offset: int = 0
) -> list:
    order_col = inspect(model).columns["id"]
    result = await session.execute(
        select(model).order_by(order_col).limit(limit).offset(offset)
    )
    return list(result.scalars().all())


async def get_item(session: AsyncSession, model, item_id: int):
    return await session.get(model, item_id)


async def create_item(
    session: AsyncSession, model, payload: dict, source: str = "web_ui"
):
    data = sanitize_payload(model, payload)
    obj = model(**data)
    # Fail fast with a readable message rather than a raw NOT NULL error.
    validate_required(model, obj)
    await _validate_abbrev(session, obj, entity_id=None)
    await _validate_ipam(session, obj, entity_id=None)
    await _validate_model(session, obj, entity_id=None)
    session.add(obj)
    await session.flush()  # obtain PK
    await naming.apply_naming(session, obj)
    await _sync_abbrev(session, obj)
    await _autoreserve_gateway(session, obj)
    await session.flush()
    for field, value in data.items():
        await _log(session, model.__tablename__, obj.id, field, None, value, source)
    await session.commit()
    await session.refresh(obj)
    return obj


async def update_item(
    session: AsyncSession, model, item_id: int, payload: dict, source: str = "web_ui"
):
    obj = await session.get(model, item_id)
    if obj is None:
        return None
    data = sanitize_payload(model, payload)
    changes: list[tuple[str, Any, Any]] = []
    for field, new_value in data.items():
        old_value = getattr(obj, field)
        if _to_str(old_value) != _to_str(new_value):
            changes.append((field, old_value, new_value))
            setattr(obj, field, new_value)
    if changes:
        validate_required(model, obj)
        await _validate_abbrev(session, obj, entity_id=obj.id)
        await _validate_ipam(session, obj, entity_id=obj.id)
        await _validate_model(session, obj, entity_id=obj.id)
        await session.flush()
        await naming.apply_naming(session, obj)
        await _sync_abbrev(session, obj)
        await session.flush()
        for field, old, new in changes:
            await _log(session, model.__tablename__, obj.id, field, old, new, source)
        await session.commit()
        await session.refresh(obj)
    return obj


async def delete_item(
    session: AsyncSession, model, item_id: int, source: str = "web_ui"
) -> bool:
    obj = await session.get(model, item_id)
    if obj is None:
        return False
    await _log(session, model.__tablename__, item_id, "__deleted__", "exists", None, source)
    if type(obj) in abbrev.ABBR_FIELDS:
        await abbrev.remove_registry(session, obj.__tablename__, obj.id)
    await session.delete(obj)
    await session.commit()
    return True


import ipaddress as _ipaddress

_IP_TYPES = (
    _ipaddress.IPv4Address,
    _ipaddress.IPv6Address,
    _ipaddress.IPv4Network,
    _ipaddress.IPv6Network,
    _ipaddress.IPv4Interface,
    _ipaddress.IPv6Interface,
)


def to_dict(obj) -> dict:
    if obj is None:
        return {}
    result = {}
    for c in inspect(type(obj)).columns:
        value = getattr(obj, c.key)
        if isinstance(value, _IP_TYPES):
            value = str(value)
        result[c.key] = value
    return result
