"""Generic async CRUD service with automatic changelog + naming.

Every create/update/delete records field-level entries in ``change_log`` and
re-computes auto-generated name fields via the naming engine.
"""
from __future__ import annotations

from typing import Any, Optional

from sqlalchemy import inspect, select
from sqlalchemy.ext.asyncio import AsyncSession

from . import abbrev, models, naming

# Auto-generated columns must never be set directly by clients.
COMPUTED_FIELDS = {
    "vf_long_name",
    "vf_short_name",
    "tia606b_name",
    "vf_friendly_name",
    "created_at",
    "updated_at",
    "id",
}

# Per-model computed columns that must never be set directly by clients. Kept
# separate from the global COMPUTED_FIELDS because these column names (e.g.
# "label") are legitimately user-editable on OTHER models.
MODEL_COMPUTED_FIELDS: dict = {
    # FEAT-6 (6C): Cable.label is generated by naming.generate_cable.
    models.Cable: {"label"},
}


def _columns(model) -> set[str]:
    return {c.key for c in inspect(model).columns}


def _to_str(value: Any) -> Optional[str]:
    if value is None:
        return None
    return str(value)


def sanitize_payload(model, payload: dict) -> dict:
    cols = {c.key: c for c in inspect(model).columns}
    computed = COMPUTED_FIELDS | MODEL_COMPUTED_FIELDS.get(model, set())
    clean: dict[str, Any] = {}
    for key, value in payload.items():
        if key in computed:
            continue
        if key in cols:
            if isinstance(value, str) and value.strip() == "":
                value = None
            if value is None:
                column = cols[key]
                # A cleared value on a NOT NULL column that has a default must
                # fall back to that default (e.g. site_code_type -> "auto")
                # instead of being written as an explicit NULL.
                if not column.nullable and (
                    column.default is not None or column.server_default is not None
                ):
                    continue
            clean[key] = value
    return clean


def humanize_field(field: str) -> str:
    """Turn a column name into the label the UI shows ("site_id" -> "Site")."""
    name = field[:-3] if field.endswith("_id") else field
    return name.replace("_", " ").strip().title()


def missing_required(model, obj) -> list[str]:
    """Columns the database declares NOT NULL that are still unset.

    Columns with a Python-side or server-side default are skipped: SQLAlchemy /
    PostgreSQL fills those in on flush.
    """
    missing: list[str] = []
    for col in inspect(model).columns:
        if col.primary_key or col.nullable:
            continue
        if col.default is not None or col.server_default is not None:
            continue
        if getattr(obj, col.key, None) is None:
            missing.append(col.key)
    return missing


def validate_required(model, obj) -> None:
    """Raise a readable 422 instead of letting Postgres emit a NOT NULL error.

    The frontend surfaces ``detail`` verbatim in its error toast, so the message
    must name the fields in the same words the grid headers use (BUG-C).
    """
    missing = missing_required(model, obj)
    if not missing:
        return
    from fastapi import HTTPException

    labels = ", ".join(f"'{humanize_field(f)}'" for f in missing)
    plural = "s" if len(missing) > 1 else ""
    raise HTTPException(
        status_code=422,
        detail=(
            f"Missing required field{plural}: {labels}. "
            f"Set {'them' if len(missing) > 1 else 'it'} on the row before saving "
            f"— the database does not allow empty values here."
        ),
    )


async def _validate_abbrev(session: AsyncSession, obj, entity_id) -> None:
    """Normalise the abbreviation/code and validate charset + global uniqueness.

    Runs BEFORE the row is flushed so clients receive a clean 422/409 error
    instead of a raw database CHECK / unique-index violation. The value is
    normalised in place according to the record's ``case_enforcement``.
    """
    field = abbrev.ABBR_FIELDS.get(type(obj))
    if field is None:
        return
    value = getattr(obj, field, None)
    if not value:
        return
    value = abbrev.apply_case(value, getattr(obj, "case_enforcement", None))
    setattr(obj, field, value)
    abbrev.validate_charset(value, field)
    conflict = await abbrev._conflict(
        session, value, obj.__tablename__, entity_id
    )
    if conflict is not None:
        from fastapi import HTTPException

        raise HTTPException(
            status_code=409,
            detail=(
                f"Abbreviation '{value}' is already used by "
                f"{conflict.entity_type} #{conflict.entity_id}. "
                "Abbreviations must be globally unique (case-insensitive)."
            ),
        )


async def _sync_abbrev(session: AsyncSession, obj) -> None:
    """Write / update / remove the global registry row for a saved record.

    The value was already normalised + validated by ``_validate_abbrev`` before
    flush; this only persists the registry ownership row.
    """
    field = abbrev.ABBR_FIELDS.get(type(obj))
    if field is None:
        return
    value = getattr(obj, field, None)
    await abbrev.sync_registry(
        session, obj.__tablename__, obj.id, field, value or None
    )


import ipaddress as _ip


def _http409(detail: str):
    from fastapi import HTTPException

    return HTTPException(status_code=409, detail=detail)


async def _validate_vlan_unique(session: AsyncSession, obj, entity_id) -> None:
    """Enforce GLOBAL uniqueness of ``vlan_id`` across all sites (decision Q1).

    A VLAN number may exist on only one site. Raises a clean 409 explaining the
    conflict instead of surfacing a raw unique-index violation.
    """
    vlan_id = getattr(obj, "vlan_id", None)
    if vlan_id is None:
        return
    stmt = select(models.Vlan).where(models.Vlan.vlan_id == vlan_id)
    if entity_id is not None:
        stmt = stmt.where(models.Vlan.id != entity_id)
    existing = (await session.execute(stmt)).scalars().first()
    if existing is not None:
        raise _http409(
            f"VLAN ID {vlan_id} is already in use globally"
            f" (site #{existing.site_id})."
            " VLAN IDs must be unique across all sites."
        )


async def _validate_cidr_overlap(session: AsyncSession, obj, entity_id) -> None:
    """Reject overlapping CIDRs.

    * Within the same site: any overlap is rejected (decision Q2).
    * Across sites: the *same* network may not be reused (decision Q1/Q2).
      Non-identical overlaps across different sites are allowed (different sites
      legitimately reuse private ranges).
    """
    cidr = getattr(obj, "network_cidr", None)
    if not cidr:
        return
    try:
        new_net = _ip.ip_network(str(cidr), strict=False)
    except ValueError:
        return  # invalid CIDR handled elsewhere
    model = type(obj)
    site_id = getattr(obj, "site_id", None)
    rows = (await session.execute(select(model))).scalars().all()
    for other in rows:
        if entity_id is not None and other.id == entity_id:
            continue
        if not other.network_cidr:
            continue
        try:
            other_net = _ip.ip_network(str(other.network_cidr), strict=False)
        except ValueError:
            continue
        if other_net.version != new_net.version:
            continue
        same_site = site_id is not None and other.site_id == site_id
        if same_site and new_net.overlaps(other_net):
            raise _http409(
                f"CIDR {new_net} overlaps existing segment {other_net}"
                f" (subnet #{other.id}) in the same site."
                " Overlapping subnets are not allowed within a site."
            )
        if not same_site and new_net == other_net:
            raise _http409(
                f"CIDR {new_net} is already used by site #{other.site_id}"
                f" (subnet #{other.id})."
                " The same network may not be reused on another site."
            )


async def _validate_ipam(session: AsyncSession, obj, entity_id) -> None:
    """Dispatch IPAM integrity checks based on the model type."""
    if isinstance(obj, models.Vlan):
        await _validate_vlan_unique(session, obj, entity_id)
    elif isinstance(obj, (models.SubnetIpv4, models.SubnetIpv6)):
        await _validate_cidr_overlap(session, obj, entity_id)


# FEAT-6 (6C): accepted cable media categories. cable_type stays a String
# column (no enum migration); this guard enforces the allowed set in code.
CABLE_TYPES = {"copper", "fiber", "power", "patchcord", "structured"}


def _validate_cable(obj: "models.Cable") -> None:
    """Validate a Cable before flush (runs on create + update).

    * ``cable_type`` must be one of CABLE_TYPES  -> 422
    * a cable may not connect a port to itself   -> 400
    """
    from fastapi import HTTPException

    cable_type = (obj.cable_type or "").strip().lower()
    if cable_type and cable_type not in CABLE_TYPES:
        raise HTTPException(
            status_code=422,
            detail=(
                f"Invalid cable_type '{obj.cable_type}'. Allowed values: "
                + ", ".join(sorted(CABLE_TYPES))
                + "."
            ),
        )
    # Self-connect: same end referenced on both A and B (type + id both set
    # and equal). Empty ends are allowed (a half-recorded cable).
    a = (obj.port_a_type, obj.port_a_id)
    b = (obj.port_b_type, obj.port_b_id)
    if a[1] is not None and b[1] is not None:
        a_norm = ((a[0] or "").strip().lower(), a[1])
        b_norm = ((b[0] or "").strip().lower(), b[1])
        if a_norm == b_norm:
            raise HTTPException(
                status_code=400,
                detail="A cable cannot connect a port to itself.",
            )


def _validate_entity_type_def(obj) -> None:
    """Phase 5 Task 16 — every capability must be one of the fixed,
    code-known CAPABILITY_VALUES (unlike field/entity type slugs, this list
    isn't itself user-definable, since each one gates real integration
    code)."""
    from fastapi import HTTPException

    caps = obj.capabilities or []
    if not isinstance(caps, list):
        raise HTTPException(
            status_code=422, detail="'Capabilities' must be a list of capability names."
        )
    unknown = sorted(set(caps) - set(models.CAPABILITY_VALUES))
    if unknown:
        raise HTTPException(
            status_code=422,
            detail=(
                f"Unknown capability/ies: {', '.join(unknown)}. Allowed values: "
                + ", ".join(models.CAPABILITY_VALUES)
                + "."
            ),
        )


def _validate_generic_entity(obj) -> None:
    """Phase 5 Task 18 — `attributes` must be a JSON object (dict), since it
    is keyed by EntityFieldDef.key. Per-field/required-field validation
    against the owning Entity_Type_Def's fields belongs to the generic form
    layer (Task 20), not this app-wide CRUD layer."""
    from fastapi import HTTPException

    if obj.attributes is not None and not isinstance(obj.attributes, dict):
        raise HTTPException(
            status_code=422, detail="'Attributes' must be an object of field key/value pairs."
        )


async def _validate_model(session: AsyncSession, obj, entity_id) -> None:
    """Model-specific validation dispatch (beyond abbrev + IPAM)."""
    if isinstance(obj, models.Cable):
        _validate_cable(obj)
    elif isinstance(obj, models.EntityTypeDef):
        _validate_entity_type_def(obj)
    elif isinstance(obj, models.GenericEntity):
        _validate_generic_entity(obj)


async def _autoreserve_gateway(session: AsyncSession, obj) -> None:
    """Auto-create a locked "Gateway" reservation for an IPv4 subnet (Q6).

    When a subnet is created with a gateway value, one locked reservation is
    created for it. Idempotent: skips if a gateway reservation already exists.
    """
    if not isinstance(obj, models.SubnetIpv4):
        return
    gateway = getattr(obj, "gateway", None)
    if not gateway:
        return
    gw = str(gateway).split("/")[0]
    existing = (
        await session.execute(
            select(models.SubnetRoleAssignment).where(
                models.SubnetRoleAssignment.subnet_ipv4_id == obj.id,
                models.SubnetRoleAssignment.ipv4_address == gw,
            )
        )
    ).scalars().first()
    if existing is not None:
        return
    session.add(
        models.SubnetRoleAssignment(
            subnet_ipv4_id=obj.id,
            role="gateway",
            label="Gateway",
            ipv4_address=gw,
            is_locked=True,
        )
    )


def _interface_own_label(obj: "models.DeviceInterface") -> str:
    """The label an interface is identified by on its own end of a Cable —
    identical fallback chain to ``ports.candidate_ports()``'s ``label`` and
    what the manual Connect panel writes as ``label_a``/``label_b``."""
    return obj.description or (f"port {obj.port_number}" if obj.port_number else f"if#{obj.id}")


async def _sync_cable_for_interface(
    session: AsyncSession, obj, prior_label_a: Optional[str] = None
) -> None:
    """Cable_Sync_Service (Phase 4 Requirement 20).

    Keeps a Cable row in sync with a DeviceInterface's connected-* fields:
    set them -> create-or-update an auto-generated Cable; clear them ->
    delete that Cable, but ONLY if it was auto-generated (20.3 — a manually
    created cable is never touched, even if it happens to describe the same
    two ports). Mirrors ``_autoreserve_gateway``'s style (direct session
    manipulation, no nested commit) rather than calling the public
    ``create_item``/``update_item``/``delete_item`` wrappers, so this rides
    the SAME outer transaction as the DeviceInterface write.

    Cable.port_a_id/port_b_id are OWNING-DEVICE ids, not interface ids (every
    port on a device shares the owner id) — label_a/label_b are what
    disambiguate the specific port, exactly like the manual Connect panel
    writes them. This hook finds "the" auto-generated cable for THIS port by
    (owner, label) since there is no unique constraint on Cable to rely on
    instead. ``prior_label_a`` is the interface's OWN label as it was BEFORE
    this update (passed by ``update_item``, which reads it before mutating
    ``obj``) — without it, changing ``description``/``port_number`` (which
    changes the computed label) would make the lookup miss the cable it
    already owns and create an orphaned duplicate instead of updating it.
    """
    if not isinstance(obj, models.DeviceInterface):
        return

    from . import ports as ports_module  # local import: ports.py imports models, not crud

    owner_type, owner_id = ports_module.interface_owner(obj)
    if not owner_type or owner_id is None:
        return  # an interface with no resolvable owner can't be cabled

    label_a = _interface_own_label(obj)
    lookup_label = prior_label_a if prior_label_a is not None else label_a

    existing = (
        await session.execute(
            select(models.Cable).where(
                models.Cable.auto_generated.is_(True),
                models.Cable.port_a_type == owner_type,
                models.Cable.port_a_id == owner_id,
                models.Cable.label_a == lookup_label,
            )
        )
    ).scalars().first()

    is_connected = bool(obj.connected_device_type) and obj.connected_device_id is not None

    if not is_connected:
        # Requirement 20.2 — cleared connected-* fields delete the Cable,
        # but only when it's ours.
        if existing is not None:
            await _log(session, "cables", existing.id, "__deleted__", "exists", None, "auto_sync")
            await session.delete(existing)
        return

    if existing is None:
        # Requirement 20.1 — create.
        cable = models.Cable(
            cable_type="patchcord",
            auto_generated=True,
            port_a_type=owner_type,
            port_a_id=owner_id,
            port_b_type=obj.connected_device_type,
            port_b_id=obj.connected_device_id,
            label_a=label_a,
            label_b=obj.connected_port,
        )
        _validate_cable(cable)
        session.add(cable)
        await session.flush()
        await naming.generate_cable(session, cable)
        for field, value in (
            ("cable_type", cable.cable_type),
            ("auto_generated", cable.auto_generated),
            ("port_a_type", cable.port_a_type),
            ("port_a_id", cable.port_a_id),
            ("port_b_type", cable.port_b_type),
            ("port_b_id", cable.port_b_id),
            ("label_a", cable.label_a),
            ("label_b", cable.label_b),
        ):
            await _log(session, "cables", cable.id, field, None, value, "auto_sync")
        return

    # Requirement 20.1 — update. The far end can change, and so can the near
    # end's OWN label if description/port_number changed (keep label_a in
    # sync with the rename rather than leaving it stale).
    changed = False
    for field, value in (
        ("port_b_type", obj.connected_device_type),
        ("port_b_id", obj.connected_device_id),
        ("label_b", obj.connected_port),
        ("label_a", label_a),
    ):
        old = getattr(existing, field)
        if old != value:
            await _log(session, "cables", existing.id, field, old, value, "auto_sync")
            setattr(existing, field, value)
            changed = True
    if changed:
        _validate_cable(existing)
        await naming.generate_cable(session, existing)


async def _log(
    session: AsyncSession,
    table: str,
    record_id: int,
    field: str,
    old: Any,
    new: Any,
    source: str,
) -> None:
    session.add(
        models.ChangeLog(
            table_name=table,
            record_id=record_id,
            field_name=field,
            old_value=_to_str(old),
            new_value=_to_str(new),
            change_source=source,
        )
    )


async def list_items(
    session: AsyncSession, model, limit: int = 1000, offset: int = 0
) -> list:
    order_col = inspect(model).columns["id"]
    result = await session.execute(
        select(model).order_by(order_col).limit(limit).offset(offset)
    )
    return list(result.scalars().all())


async def get_item(session: AsyncSession, model, item_id: int):
    return await session.get(model, item_id)


async def create_item(
    session: AsyncSession, model, payload: dict, source: str = "web_ui"
):
    data = sanitize_payload(model, payload)
    obj = model(**data)
    # Fail fast with a readable message rather than a raw NOT NULL error.
    validate_required(model, obj)
    await _validate_abbrev(session, obj, entity_id=None)
    await _validate_ipam(session, obj, entity_id=None)
    await _validate_model(session, obj, entity_id=None)
    session.add(obj)
    await session.flush()  # obtain PK
    await naming.apply_naming(session, obj)
    await _sync_abbrev(session, obj)
    await _autoreserve_gateway(session, obj)
    await _sync_cable_for_interface(session, obj)
    await session.flush()
    for field, value in data.items():
        await _log(session, model.__tablename__, obj.id, field, None, value, source)
    await session.commit()
    await session.refresh(obj)
    return obj


async def update_item(
    session: AsyncSession, model, item_id: int, payload: dict, source: str = "web_ui"
):
    obj = await session.get(model, item_id)
    if obj is None:
        return None
    # Snapshot BEFORE any mutation below — the Cable_Sync_Service needs the
    # interface's own label as it was prior to this update, in case
    # description/port_number (which the label is derived from) is changing.
    prior_label_a = _interface_own_label(obj) if isinstance(obj, models.DeviceInterface) else None
    data = sanitize_payload(model, payload)
    changes: list[tuple[str, Any, Any]] = []
    for field, new_value in data.items():
        old_value = getattr(obj, field)
        if _to_str(old_value) != _to_str(new_value):
            changes.append((field, old_value, new_value))
            setattr(obj, field, new_value)
    if changes:
        validate_required(model, obj)
        await _validate_abbrev(session, obj, entity_id=obj.id)
        await _validate_ipam(session, obj, entity_id=obj.id)
        await _validate_model(session, obj, entity_id=obj.id)
        await session.flush()
        await naming.apply_naming(session, obj)
        await _sync_abbrev(session, obj)
        await _sync_cable_for_interface(session, obj, prior_label_a=prior_label_a)
        await session.flush()
        for field, old, new in changes:
            await _log(session, model.__tablename__, obj.id, field, old, new, source)
        await session.commit()
        await session.refresh(obj)
    return obj


async def delete_item(
    session: AsyncSession, model, item_id: int, source: str = "web_ui"
) -> bool:
    obj = await session.get(model, item_id)
    if obj is None:
        return False
    # Phase 5 Task 15 — a builtin FieldTypeDef (one of the 6 seeded storage
    # kinds) can never be deleted: entity_field_defs (Task 17) will reference
    # these by id, and the generic form/grid layer assumes all 6 storage
    # kinds always exist.
    if isinstance(obj, models.FieldTypeDef) and obj.builtin:
        from fastapi import HTTPException

        raise HTTPException(
            status_code=400,
            detail=f"'{obj.label}' is a built-in field type and cannot be deleted.",
        )
    await _log(session, model.__tablename__, item_id, "__deleted__", "exists", None, source)
    if type(obj) in abbrev.ABBR_FIELDS:
        await abbrev.remove_registry(session, obj.__tablename__, obj.id)
    await session.delete(obj)
    await session.commit()
    return True


import ipaddress as _ipaddress

_IP_TYPES = (
    _ipaddress.IPv4Address,
    _ipaddress.IPv6Address,
    _ipaddress.IPv4Network,
    _ipaddress.IPv6Network,
    _ipaddress.IPv4Interface,
    _ipaddress.IPv6Interface,
)


def to_dict(obj) -> dict:
    if obj is None:
        return {}
    result = {}
    for c in inspect(type(obj)).columns:
        value = getattr(obj, c.key)
        if isinstance(value, _IP_TYPES):
            value = str(value)
        result[c.key] = value
    return result
